insert into career (id_career, name) values (1, 'Akita University of Economics and Law');
insert into career (id_career, name) values (2, 'Suwon Catholic University');
insert into career (id_career, name) values (3, 'Tohoku Fukushi University');
insert into career (id_career, name) values (4, 'Zanjan University');
insert into career (id_career, name) values (5, 'Azusa Pacific University');
insert into career (id_career, name) values (6, 'China Foreign Affairs University');
insert into career (id_career, name) values (7, 'Qom University');
insert into career (id_career, name) values (8, 'Asa University Bangladesh');
insert into career (id_career, name) values (9, 'Australlian College of Kuwait ');
insert into career (id_career, name) values (10, 'Al-Yamamah College');
insert into career (id_career, name) values (11, 'Universität Hannover');
insert into career (id_career, name) values (12, 'Royal University of Phnom Penh');
insert into career (id_career, name) values (13, 'Islamic Azad University, Khorasgan');
insert into career (id_career, name) values (14, 'University of Wisconsin - Green Bay');
insert into career (id_career, name) values (15, 'National Museum Institute of History of Art, Conservation and Museology');
insert into career (id_career, name) values (16, 'Vanguard University of Southern California');
insert into career (id_career, name) values (17, 'Pacific University');
insert into career (id_career, name) values (18, 'Kwantleen University College');
insert into career (id_career, name) values (19, 'Grantham University');
insert into career (id_career, name) values (20, 'Hawassa University');
